In [2]:
import numpy as np

print('''Welcome to Connect Four! This is a 2-player game. Player 1 uses '1' as their game piece, and Player 2 uses '2'. The goal is to connect four of your pieces horizontally, vertically, or diagonally to win.''')

def create_board():
    return np.zeros((6, 7))

def is_valid_loc(board, col):
    return board[5][col] == 0

def drop_piece(board, col, piece):
    for row in range(6):
        if board[row][col] == 0:
            board[row][col] = piece
            break
            
def winning_rule(board, piece):
    # Check horizontal locations for win
    for row in range(6):
        for col in range(4):
            if (board[row][col] == piece and board[row][col + 1] == piece and board[row][col + 2] == piece and board[row][col + 3] == piece):
                return True
            
     # Check vertical locations for win
    for row in range(3):
        for col in range(7):
            if (board[row][col] == piece and board[row + 1][col] == piece and board[row + 2][col] == piece and board[row + 3][col] == piece):
                return True
     # Check positive sloped diagonals       
    for row in range(3):
        for col in range(4):
            if (board[row][col] == piece and board[row + 1][col + 1] == piece and board[row + 2][col + 2] == piece and board[row + 3][col + 3] == piece):
                return True
     # Check negative sloped diagonals       
    for row in range(3):
        for col in range(4):
            if (board[row][col] == piece and board[row + 1][col - 1] == piece and board[row + 2][col - 2] == piece and board[row + 3][col - 3] == piece):
                return True

def f_board(board):
    print(np.flip(board,0))
    
board = create_board()
game_over = False
turn = 0  
repeat = False
while not game_over or repeat:
    f_board(board)
    if turn == 0:
        print("Player 1, it's your turn! Enter the column number (0-6) where you want to drop your piece: ")
        piece = 1
    else:
        print("Player 2, it's your turn! Enter the column number (0-6) where you want to drop your piece")
        piece = 2

    try:
        col = int(input())
        if col < 0 or col > 6:
            print("Invalid input. Please enter a number between 0 and 6 to select a column.")
            continue
        if not is_valid_loc(board, col):
            print("That column is already full. Choose a different column.")
            continue

        drop_piece(board, col, piece)

        if winning_rule(board, piece):
            f_board(board)
            print(f"Player {piece} Won the game!!! Congrats!")
            game_over = True
        elif np.count_nonzero(board) == 6 * 7:
            f_board(board)
            print("It's a tie! The board is full.")
            game_over = True

        turn = 1 - turn  # Switch turns
    except ValueError:
        print("Invalid input. Please enter a number between 0 and 6 to select a column.")
one_more_time = input("Do you want to play again? (yes/no)").lower()
if one_more_time == "yes":
    repeat=False
else:
    print("Thank you for playing!")
        




Welcome to Connect Four! This is a 2-player game. Player 1 uses '1' as their game piece, and Player 2 uses '2'. The goal is to connect four of your pieces horizontally, vertically, or diagonally to win.
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Player 1, it's your turn! Enter the column number (0-6) where you want to drop your piece: 
0
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
Player 2, it's your turn! Enter the column number (0-6) where you want to drop your piece
1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0. 0. 0.]]
Player 1, it's your turn! Enter the column number (0-6) where you want to drop your piece: 
1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0.